---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/importer/sessions":
    post:
      summary: Create Session
      description: Use this endpoint to generate an importer session token based on an importer slug. The session token should be used as part of creating a fuse importer instance.
      tags:
      - Create Session
      security:
      - bearer: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for the importer session
                required:
                - token
        '422':
          description: unprocessable entity
        '404':
          description: importer not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                importer_slug:
                  type: string
                  description: Importer Slug
                meta:
                  type: object
                  description: Contains meta information about the importer session which can contain user related information
              required:
              - importer_slug

  "/api/v1/imports/{import_slug}/records":
    get:
      summary: Import Records
      tags:
      - Records
      security:
      - bearer: []
      parameters:
      - name: import_slug
        in: path
        required: true
        description: Import Slug
        schema:
          type: string
      - name: page
        in: query
        description: The page number for pagination
        schema:
          type: integer
      - name: per_page
        in: query
        description: Number of records per page, maximum of 100
        schema:
          type: integer
      responses:
        '200':
          description: A paginated list of records for a particular import
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        slug:
                          type: string
                          format: uuid
                          description: The slug of the record
                        data:
                          type: object
                          additionalProperties: {}
                          description: An object containing record data
                        created_at:
                          type: string
                          format: date-time
                          description: The timestamp of creation for the record
                        updated_at:
                          type: string
                          format: date-time
                          description: The timestamp of last update for the record
                        sort:
                          type: integer
                          description: The sort order
                      required:
                      - slug
                      - data
                      - created_at
                      - updated_at
                      - sort
                  metadata:
                    type: object
                    description: Metadata associated with the import session
                required:
                - data
                - metadata
        '404':
          description: import not found
        '401':
          description: unauthorized

  "/api/v1/imports":
    get:
      summary: List Imports
      tags:
      - imports
      security:
      - bearer: []
      parameters:
      - name: page
        in: query
        description: The page number for pagination
        schema:
          type: integer
      - name: per_page
        in: query
        description: Number of records per page, maximum of 100
        schema:
          type: integer
      - name: status
        in: query
        schema:
          type: string
      responses:
        '200':
          description: filtered imports found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    description: A paginated list of imports
                    items:
                      type: object
                      properties:
                        slug:
                          type: string
                          format: uuid
                          description: The slug of the import
                        row_count:
                          type: integer
                          description: The number of rows in the import
                        created_at:
                          type: string
                          format: date-time
                          description: The timestamp of creation for the import
                        updated_at:
                          type: string
                          format: date-time
                          description: The timestamp of last update for the import
                        status:
                          type: string
                          enum:
                          - created
                          - submitting
                          - submitted
                          - completed
                          description: The status of the import
                        template:
                          type: object
                          properties:
                            name:
                              type: string
                            slug:
                              type: string
                              format: uuid
                          required:
                          - name
                          - slug
                        metadata:
                          type: object
                          description: Additional metadata for the import
                      required:
                      - slug
                      - row_count
                      - created_at
                      - updated_at
                      - status
                required:
                - data
        '401':
          description: unauthorized

  "/api/v1/imports/{id}":
    get:
      summary: Retrieves a specific import
      tags:
        - imports
      description: Get details of a specific import by ID.
      security:
        - bearer: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Import details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  slug:
                    type: string
                  row_count:
                    type: integer
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  status:
                    type: string
                    enum:
                      - created
                      - submitting
                      - submitted
                      - completed
                  template:
                    type: object
                    properties:
                      name:
                        type: string
                      slug:
                        type: string
                  metadata:
                    type: object
                    nullable: true
                required:
                  - slug
                  - row_count
                  - created_at
                  - updated_at
                  - status
        '404':
          description: Import not found
        '401':
          description: unauthorized

servers:
- url: https://fuse.flatirons.com
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
